# 精准率与召回率的平衡

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn import datasets

digits = datasets.load_digits()
X = digits.data
y = digits.target.copy()

y[digits.target==9] = 1
y[digits.target!=9] = 0

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=666)

In [4]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
y_predict = log_reg.predict(X_test)

D:\anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [5]:
from sklearn.metrics import f1_score

f1_score(y_test, y_predict)

0.8674698795180723

In [6]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_predict)

array([[403,   2],
       [  9,  36]], dtype=int64)

In [7]:
from sklearn.metrics import precision_score

precision_score(y_test, y_predict)

0.9473684210526315

In [8]:
from sklearn.metrics import recall_score

recall_score(y_test, y_predict)

0.8

In [22]:
 # 逻辑回归中做决策方法，从这里下手来修改决策边界。
log_reg.decision_function(X_test)[:10]
# 返回的结果是X_test这个这些数据对应的score是多少，看大于0还是小于0做决定

array([-21.46979753, -32.9639392 , -16.39403147, -79.92666239,
       -48.19595005, -24.21881435, -44.77416219, -24.22493782,
        -1.23230564, -19.07343986])

In [10]:
log_reg.predict(X_test)[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
decision_scores = log_reg.decision_function(X_test)

In [12]:
np.min(decision_scores)

-85.7668468413466

In [13]:
np.max(decision_scores)

19.97722962234501

In [14]:
y_predict_2 = np.array(decision_scores >= 5, dtype='int') # 使用5作为决策边界

In [15]:
confusion_matrix(y_test, y_predict_2)

array([[404,   1],
       [ 21,  24]], dtype=int64)

In [16]:
precision_score(y_test, y_predict_2)

0.96

In [17]:
recall_score(y_test, y_predict_2)

0.5333333333333333

In [18]:
y_predict_3 = np.array(decision_scores >= -5, dtype='int') # 使用-5作为决策边界

In [19]:
confusion_matrix(y_test, y_predict_3)

array([[389,  16],
       [  5,  40]], dtype=int64)

In [20]:
precision_score(y_test, y_predict_3)

0.7142857142857143

In [21]:
recall_score(y_test, y_predict_3)

0.8888888888888888