## 03 测试我们的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets 

In [2]:
iris = datasets.load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [3]:
X = iris.data

In [4]:
y = iris.target

In [5]:
X.shape

(150, 4)

In [6]:
y.shape

(150,)

### train_test_split

分离出一部分数据做训练，另外一部分数据做测试。

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
shuffled_indexes = np.random.permutation(len(X))
shuffled_indexes

array([127,  10,  65,  36,   4,  34,  16,  26, 145,  52,  13,  55,  77,
        91,  76, 139, 132,  27, 137,   0,  58,  81,  72,  62,  97,  23,
        67,  93,  98,  47,  96,  30, 117, 115,  78,  94, 149,  68,  90,
        22, 104,  53,   8, 116,  66,   9, 147,  88, 125,  80,  60, 128,
        40,  54,  75,  37,  43,   1, 120, 119,  57,  41,  86, 135,  63,
       133,   5,  70, 138, 108,  24, 122, 141, 130,  69,  61, 126,  18,
       121,  19,  84,  20,  14,  87, 148,  33, 142,  95,  74,  39,  28,
        73,  25, 105, 134,  50,  85,  12, 144,   7, 123,  44, 118, 109,
       114, 101,  79, 106,  15, 113,  89,  92, 146,  46,  29,  99, 129,
        49,  35,  38,  82, 140,   6, 136,  31, 103, 124,  71, 110,  83,
       131,   2, 102,  59,  64, 111,  51, 112, 107,  48,  11,  42,  17,
        56,  32,  45,  21, 100,   3, 143])

In [9]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [10]:
test_indexes = shuffled_indexes[:test_size]
train_indexes = shuffled_indexes[test_size:]

In [11]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [12]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [13]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 封装

In [14]:
from playML.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [15]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [16]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 测试我们的算法

In [17]:
from playML.KNN import KNNClassifier

my_knn_clf = KNNClassifier(k=3)
my_knn_clf.fit(X_train, y_train)
y_predict = my_knn_clf.predict(X_test)

In [18]:
y_predict

array([2, 1, 0, 1, 0, 0, 2, 0, 2, 0, 2, 2, 0, 1, 1, 1, 1, 1, 1, 0, 2, 1,
       2, 1, 1, 0, 2, 2, 0, 2])

In [19]:
y_test

array([2, 1, 0, 1, 0, 0, 2, 0, 2, 0, 2, 2, 0, 1, 1, 1, 1, 1, 1, 0, 2, 1,
       2, 1, 1, 0, 2, 2, 0, 2])

In [20]:
sum(y_predict == y_test)

30

In [21]:
sum(y_predict == y_test) / len(y_test)

1.0

#### sklearn中的train_test_split

In [22]:
from sklearn.model_selection import train_test_split

train_test_split

<function sklearn.model_selection._split.train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)>

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [24]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [25]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
