# Numpy cheat List
Numpy 速查手册

In [3]:
import numpy as np
# check numpy version
np.__version__


'1.21.2'

In [4]:
arr = np.array([i for i in range(10)])
arr.dtype # check data the type of numpy ndim array

dtype('int32')

In [5]:
x = np.arange(10)

In [6]:
X = np.arange(15).reshape((3, 5))

In [7]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
x.ndim

1

In [9]:
X.ndim

2

In [10]:
x.shape

(10,)

In [11]:
X.shape

(3, 5)

In [12]:
x.size

10

In [13]:
X.size

15

Data Access

In [14]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x[0]

0

In [16]:
x[-1]

9

In [17]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
X[0][0] # 不建议！

0

In [19]:
X[0, 0]

0

In [20]:
X[0, -1]

4

In [21]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
x[0:5]

array([0, 1, 2, 3, 4])

In [23]:
x[:5]

array([0, 1, 2, 3, 4])

In [24]:
x[5:]

array([5, 6, 7, 8, 9])

In [25]:
x[4:7]

array([4, 5, 6])

In [26]:
x[::2]

array([0, 2, 4, 6, 8])

In [27]:
x[1::2]

array([1, 3, 5, 7, 9])

In [28]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [29]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [31]:
X[:2][:3] # 结果不一样，在numpy中使用","做多维索引

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [33]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [34]:
X[0, :]

array([0, 1, 2, 3, 4])

In [35]:
X[:, 0]

array([ 0,  5, 10])

In [36]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [37]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [38]:
X[0, 0] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [40]:
subX = X[:2, :3].copy()

In [41]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [42]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Re shape

In [43]:
x.shape

(10,)

In [44]:
x.ndim

1

In [45]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
A = x.reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [48]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
B = x.reshape(1, 10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [50]:
B.ndim

2

In [51]:
B.shape

(1, 10)

In [52]:
x.reshape(-1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [53]:
x.reshape(10, -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [54]:
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])