# Numpy Cheat List
merge and split operations

In [19]:
import numpy as np

In [20]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [21]:
# concatenate: 串联，链接，连缀
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [22]:
z = np.array([666, 666, 666])
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [23]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [24]:
np.concatenate([A, A], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [25]:
np.concatenate([A, z.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [26]:
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [27]:
B = np.full((2,2), 100)

In [28]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

splits

In [29]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
x1, x2, x3 = np.split(x, [3, 7])

In [31]:
x1

array([0, 1, 2])

In [32]:
x2

array([3, 4, 5, 6])

In [33]:
x3

array([7, 8, 9])

In [34]:
x1, x2 = np.split(x, [5])

In [35]:
x1

array([0, 1, 2, 3, 4])

In [36]:
x2

array([5, 6, 7, 8, 9])

In [37]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
A1, A2 = np.split(A, [2])

In [39]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [40]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
A1, A2 = np.split(A, [2], axis=1)

In [42]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [43]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [44]:
upper, lower = np.vsplit(A, [2])

In [45]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [46]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
left, right = np.hsplit(A, [2])

In [48]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [49]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [50]:
data = np.arange(16).reshape((4, 4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
X, y = np.hsplit(data, [-1])

In [52]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [53]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [54]:
y[:, 0]

array([ 3,  7, 11, 15])