# Numpy 中arg运算

In [1]:
import numpy as np

In [2]:
x = np.random.normal(0, 1, 1000000)

### 索引

In [3]:
# 最小的元素的索引
np.argmin(x)

949538

In [4]:
x[np.argmin(x)] == np.min(x)

True

In [5]:
np.argmax(x)

476825

# 排序和使用索引

In [6]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [7]:
np.random.shuffle(x)
x

array([ 2,  6, 12, 13,  4, 15,  7,  9,  3,  5,  0,  1, 11, 14, 10,  8])

In [8]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [9]:
x.sort()

In [10]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [11]:
X = np.random.randint(10, size=(4,4))
X

array([[5, 1, 2, 2],
       [8, 4, 9, 8],
       [1, 6, 7, 8],
       [6, 0, 4, 5]])

In [12]:
np.sort(X, axis=0)

array([[1, 0, 2, 2],
       [5, 1, 4, 5],
       [6, 4, 7, 8],
       [8, 6, 9, 8]])

In [13]:
np.sort(X, axis=1)

array([[1, 2, 2, 5],
       [4, 8, 8, 9],
       [1, 6, 7, 8],
       [0, 4, 5, 6]])

### 使用索引

In [14]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
np.random.shuffle(x)

In [16]:
# 不修改原数组的内容，把排序后的数组的索引返回
np.argsort(x)

array([ 1,  8, 11, 14,  6,  0, 12,  3,  5, 13, 15,  7, 10,  9,  4,  2],
      dtype=int64)

In [17]:
# partition： 划分, 分, 隔
np.partition(x, 3)

array([ 1,  0,  2,  3,  5,  4,  6,  8,  7,  9, 10, 12, 13, 14, 15, 11])

In [18]:
np.argpartition(x, 3)

array([ 8,  1, 11, 14,  0,  6, 12,  5,  3, 13, 15, 10,  9,  4,  2,  7],
      dtype=int64)

In [19]:
X

array([[5, 1, 2, 2],
       [8, 4, 9, 8],
       [1, 6, 7, 8],
       [6, 0, 4, 5]])

In [20]:
np.argsort(X, axis=1)

array([[1, 2, 3, 0],
       [1, 0, 3, 2],
       [0, 1, 2, 3],
       [1, 2, 3, 0]], dtype=int64)

In [21]:
np.argpartition(X, 2, axis=1)

array([[1, 2, 3, 0],
       [1, 0, 3, 2],
       [0, 1, 2, 3],
       [1, 2, 3, 0]], dtype=int64)